package net.meshmc.mesh.statics;

import net.meshmc.mesh.api.block.Material;

public class StaticMaterials {
    public static final Material
            AIR = null,
            AMETHYST = null,
            ANVIL = null,
            BAMBOO = null,
            BAMBOO_SAPLING = null,
            BARRIER = null,
            BUBBLE_COLUMN = null,
            CACTUS = null,
            CAKE = null,
            CARPET = null,
            CLAY = null,
            DECORATION = null,
            DRAGON_EGG = null,
            FIRE = null,
            GLASS = null,
            GOURD = null,
            GRASS = null,
            IRON = null,
            ICE = null,
            ICE_DENSE = null,
            LAVA = null,
            LEAVES = null,
            MOSS_BLOCK = null,
            NETHER_SHOOTS = null,
            NETHER_WOOD = null,
            PISTON = null,
            PLANT = null,
            PLANT_REPLACEABLE = null,
            PLANT_UNDERWATER = null,
            PORTAL = null,
            REDSTONE_LIGHT = null,
            ROCK = null,
            SAND = null,
            SCULK = null,
            SNOW_BLOCK = null,
            SNOW_LAYER = null,
            SNOW_POWDER = null,
            SOIL = null,
            SPONGE = null,
            STRUCTURE_VOID = null,
            TNT = null,
            WATER = null,
            WEB = null,
            WOOD = null,
            WOOL = null;
}
